# Terraform template for vpc
# Generated by Cloud Craver v1.0.0

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Add your vpc configuration here
