# Terraform template for complex-vpc
# Generated by Cloud Craver


provider "aws" {
  region = "us-east-1"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Add your complex-vpc configuration here
